@namespace("ru.yandex.practicum.kafka.telemetry.event")
protocol SensorEventProtocol {

  record ClimateSensorEventAvro {
	  int temperatureC;
	  int humidity;
	  int co2_level;
  }

  record LightSensorEventAvro {
	  int link_quality;
	  int luminosity;
  }

  record MotionSensorEventAvro {
	  int link_quality;
	  boolean motion;
	  int voltage;
  }

  record TemperatureSensorEventAvro {
	  int temperatureC;
	  int temperatureF;
  }

  record SwitchSensorAvro {
	  boolean state;
  }

  record SensorEventAvro {
	  string id;
	  string hub_id;
	  timestamp_ms? timestamp;
	  union {TemperatureSensorEventAvro, MotionSensorEventAvro, LightSensorEventAvro, ClimateSensorEventAvro, SwitchSensorAvro} payload;
  }
}